
export const LOGIN_SET = "LOGIN_SET"
export const LOGIN_TOKEN = "LOGIN_TOKEN"
export const LOGIN_WITH_PROVIDER = "LOGIN_WITH_PROVIDER"
export const LOAD_CONFIG_DATA = "LOAD_CONFIG_DATA"
export const WORKER_SET="WORKER_SET";
export const  CURRENT_WORKER_SET = "CURRENT_WORKER_SET";
export const  CURRENT_CASE_RECORD_SET = "CURRENT_CASE_RECORD_SET";
export const  ALL_CASE_RECORD_SET = "ALL_CASE_RECORD_SET";
export const LOGOUT_SET = "LOGOUT_SET"
export  const DASHBOARD_FINANCE_SET="DASHBOARD_FINANCE_SET"
export const CURRENT_COMPANY_SET = "CURRENT_COMPANY_SET"
