
export const LOGIN_SET = "LOGIN_SET"
export const LOGIN_TOKEN = "LOGIN_TOKEN"
export const LOGIN_WITH_PROVIDER = "LOGIN_WITH_PROVIDER"
export const LOAD_CONFIG_DATA = "LOAD_CONFIG_DATA"
export const WORKER_SET="WORKER_SET";
export const  CURRENT_WORKER_SET = "CURRENT_WORKER_SET";
export const  CURRENT_CASE_RECORD_SET = "CURRENT_CASE_RECORD_SET";
export const  ALL_CASE_RECORD_SET = "ALL_CASE_RECORD_SET";
export const LOGOUT_SET = "LOGOUT_SET"
export  const DASHBOARD_FINANCE_SET="DASHBOARD_FINANCE_SET"
export const CURRENT_COMPANY_SET = "CURRENT_COMPANY_SET"

export const RECHARGE_NETWORK_SET = "RECHARGE_NETWORK_SET"
export const RECHARGE_TYPE_SET = "RECHARGE_TYPE_SET"
export const RECHARGE_NUMBER_SET = "RECHARGE_NUMBER_SET"
export const RECHARGE_AMOUNT_SET = "RECHARGE_AMOUNT_SET"
export const RECHARGE_PRODUCT_SET = "RECHARGE_PRODUCT_SET"

