
export const LOGIN_SET = "LOGIN_SET"
export const LOAD_CONFIG_DATA = "LOAD_CONFIG_DATA"
export const WORKER_SET="WORKER_SET";
export const  CURRENT_WORKER_SET = "CURRENT_WORKER_SET";
export const  CURRENT_CASE_RECORD_SET = "CURRENT_CASE_RECORD_SET";
export const  ALL_CASE_RECORD_SET = "ALL_CASE_RECORD_SET";